# Generated by Django 4.2.11 on 2024-03-07 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belanjainaja', '0002_alter_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping',
            name='items',
        ),
    ]
