# Generated by Django 4.2.11 on 2024-03-07 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belanjainaja', '0003_remove_shopping_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.BigIntegerField()),
                ('unit', models.CharField(max_length=10)),
                ('total_price', models.BigIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belanjainaja.item')),
                ('shopping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belanjainaja.shopping')),
            ],
        ),
        migrations.AddField(
            model_name='shopping',
            name='items',
            field=models.ManyToManyField(through='belanjainaja.ShoppingItem', to='belanjainaja.item'),
        ),
    ]
