# Generated by Django 4.2.11 on 2024-03-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belanjainaja', '0005_shopping_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
    ]
